import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
const out='scripts/verify-out';
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const errors=[];
const page=await (await browser.newContext({viewport:{width:1440,height:900}})).newPage();
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://localhost:3016/?v='+Date.now(),{waitUntil:'domcontentloaded',timeout:60000});
try{await page.waitForFunction(()=>!document.querySelector('.loading'),{timeout:90000});}catch{errors.push('loading');}
await page.waitForTimeout(1000);
const look=page.getByRole('button',{name:'Look',exact:true});
const dissect=page.getByRole('button',{name:'Dissect',exact:true});
if(!await look.getAttribute('aria-pressed'))errors.push('look missing pressed');
if(await page.getByText('Skin and hair',{exact:true}).count())errors.push('integumentary listed');
await page.screenshot({path:`${out}/ecorche.png`});
await page.keyboard.press('/');
await page.waitForTimeout(200);
await page.getByLabel('Search named anatomical structures').fill('heart');
await page.waitForTimeout(400);
await page.getByRole('option',{name:/^Heart/i}).first().click();
await page.waitForTimeout(900);
await page.screenshot({path:`${out}/ecorche-heart.png`});
await page.getByRole('toolbar',{name:'Study tools'}).getByRole('button',{name:'Isolate'}).click();
await page.waitForTimeout(700);
await page.screenshot({path:`${out}/ecorche-isolate.png`});
await page.keyboard.press('Escape');
await page.keyboard.press('Escape');
await page.keyboard.press('r');
await page.waitForTimeout(400);
await page.keyboard.press('p');
await page.waitForTimeout(300);
await page.getByRole('button',{name:'Arms raised'}).click();
await page.waitForTimeout(900);
await page.screenshot({path:`${out}/ecorche-arms.png`});
await page.keyboard.press('Escape');
await page.getByLabel('Dissection layers').click();
await page.getByRole('button',{name:'Viscera'}).click();
await page.waitForTimeout(700);
await page.screenshot({path:`${out}/ecorche-viscera.png`});
console.log(JSON.stringify({errors,hint:await page.locator('.hint').innerText(),look:await look.getAttribute('aria-pressed'),dissect:await dissect.getAttribute('aria-pressed')},null,2));
await browser.close();
if(errors.some(e=>/FRAGMENT ERROR|VERTEX ERROR|loading/i.test(e)))throw new Error(errors.join('\n'));
